Update quickstart-javascript.md
The instructions for use in a ReasonReact project are not great because they are missing `npm install`,  so the user will receive the error
```
Package not found: resolving package reason-react in /  
File "bsconfig.json", line 1
Error: package reason-react not found or built , if it is not built
Please run 'bsb -make-world', otherwise please install it
```
It would make a much better first impression if the instructions didn't require the user to debug this issue.